developer_token: "dOwHNw3vtz7NDgxre3Sh6A"
client_id: "175305419282-9187nevmjk8mfe5gng00hsmlof8i70ku.apps.googleusercontent.com"
client_secret: "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"
refresh_token: "1//05HdYGED8mVjyCgYIARAAGAUSNwF-L9Ir0k4AAn0d8lDBOYa-vnahPv7ov4pu3cNESc3KDZHP7KONlHZrKhFL0fGULWN5Bik40bA"
use_proto_plus: true
login_customer_id: "2454240798"
